name: Run Python Script

on:
  schedule:
    # 每天运行一次，例如在午夜。使用 POSIX cron 语法。
    - cron: '0 12 * * *'
    workflow_dispatch: # 允许手动触发workflow

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run script
    env:
        URL: ${{ secrets.URL }}
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        TOKEN: ${{ secrets.TOKEN }}
      run: |
        python your_script.py
