name: CheckScores

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch: # 允许手动触发workflow

jobs:
  
  CheckScores:
    runs-on: self-hosted # 在你的Self-Hosted Runner上运行

    steps:
      - name: Checkout Repository # 使用GitHub Actions提供的动作来检出代码库
        uses: actions/checkout@v2

      - name: Set up Python # 配置Python环境
        uses: actions/setup-python@v2
        with:
          python-version: 3.x # 使用Python 3.x版本

      - name: Install dependencies # 使用pip安装项目的依赖项
        run: |
          pip install requests rsa pyquery school_api cryptography

      - name: Configure Git # 配置Git用户信息
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          
      - name: Run main.py # 运行主程序main.py
        run: python main.py
        env:
          URL: ${{ secrets.URL }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          YEAR: ${{ secrets.YEAR }}
          TERM: ${{ secrets.TERM }}
          TOKEN: ${{ secrets.TOKEN }}

      - name: Add changes # 将当前目录中的所有更改添加到Git的暂存区
        run: |
          git add .

      - name: Commit changes # 提交更改到Git仓库
        run: |
          git commit -m "Update from GitHub Actions" || true  # 如果没有更改，则允许提交失败，但不中断workflow

      - name: Force push changes to main branch # 将更改强制推送到main分支
        run: |
          git push origin main --force
